#!/bin/bash
cd $HOME
clear
clear
echo -e "    \033[0m\033[01;37m• \033[01;33mESCOLHA UMA DAS OPÇÕES ABAIXO \033[0m\033[01;37m•\033[0m"
echo ""
echo -e "\033[0m\033[01;37m(1) \033[01;33mTESTADOR PADRÃO\033[0m"
echo -e "\033[0m\033[01;37m(2) \033[01;33mTESTAR TOKEN PERSONALIZADO \033[0m"
echo -e "\033[0m\033[01;37m(3) \033[01;33mSAIR \033[0m"
echo " "

echo -e "\033[01;37mINFORME UMA OPÇÃO:\033[0m"
read OPTION

case $OPTION in
        (1) mbsfree1
        ;;
        (2) mbfree2
        ;;
        (3) exit
        ;;
        (*) echo -e "\033[1;31mOPCÃO INVÁLIDA!\033[1;37m"

   sleep 1
esac
clear
mbsmain
