#!/bin/bash
cd $HOME
cd $PREFIX/bin/
echo -e "\033[0m\033[01;33mBAIXANDO RECURSOS\033[03;037m"
rm mbsfree1 > /dev/null 2>&1
curl -sO https://raw.githubusercontent.com/Orlandomdp/Orlandomdp/main/mbsfree1 && chmod 777 mbsfree1 > /dev/null 2>&1
rm mbfree2 > /dev/null 2>&1
curl -sO https://raw.githubusercontent.com/Orlandomdp/Orlandomdp/main/mbfree2 && chmod 777 mbfree2 > /dev/null 2>&1
rm mbmain > /dev/null 2>&1
curl -sO https://raw.githubusercontent.com/Orlandomdp/Orlandomdp/main/mbmain && chmod 777 mbmain > /dev/null 2>&1
cd $HOME
rm mbmain > /dev/null 2>&1
clear
mbsfree
